### ISSUE TITLE
Spawn and LocalSpawn implementation

### ISSUE THREAD

**Issue by nazar-pc** [smol-rs/async-executor#25]
I'd like to see `Spawn` and `LocalSpawn` trait implementations from `futures` (now `futures-task` actually) to be implemented for executors. That would make it possible to use `async-executor` with generic code that doesn't necessarily care about specific executor being used (if I understand it correctly).

**Comment by taiki-e** [comment]
The current Spawn and LocalSpawn in `futures` are quite restrictive as a result of trying to support various use cases. So, in many cases, they are not actually used in the ecosystem. https://github.com/rust-lang/futures-rs/issues/1634

I am planning to improve it in futures 0.4, but it will take quite some time before it is released, so I am going to close this for now.
