### ISSUE TITLE
Removing lifetime parameter for Executor and LocalExecutor

### ISSUE THREAD

**Issue by IGreyGooI** [smol-rs/async-executor#26]
What is the point of it? It is not reasonable to statically track the lifetime of Executor which only contain a Arc.

**Comment by taiki-e** [comment]
IIUC, this is needed to spawn a non-static future: https://github.com/smol-rs/async-executor/commit/f9e28cd6d8ed85af9efcac870562394bb667cf59

https://github.com/smol-rs/async-executor/blob/dacd4db652a8062cedd835e4c1f9da0e4e0d32d0/src/lib.rs#L68-L69

https://github.com/smol-rs/async-executor/blob/dacd4db652a8062cedd835e4c1f9da0e4e0d32d0/tests/drop.rs#L76

See also safety requirements of [async_task::spawn_unchecked](https://docs.rs/async-task/latest/async_task/fn.spawn_unchecked.html)
