### ISSUE TITLE
Update to fastrand 2.0.0 isn't published

### ISSUE THREAD

**Issue by mwcampbell** [smol-rs/async-executor#47]
I noticed that although this crate has been updated to use fastrand 2.0.0, that update hasn't yet been published. Is there anything blocking the publication of a new version? Any way I can help?

**Comment by notgull** [comment]
I was mostly waiting for smol v2.0 (smol-rs/smol#258) to release, but if you need it now I'm happy to release.

**Comment by mwcampbell** [comment]
I'm currently working on a PR to switch zbus from rand to fastrand. zbus already depends transitively on fastrand 1.x, via smol crates (async-executor, blocking, and futures-lite). So having my PR use fastrand 1.9.0 might be a good idea, to avoid having dependencies on both versions across the dependency graph. But deliberately using an old version in a new change just seems wrong. Especially when I agree with the main breaking change of fastrand 2.0 (dropping interior mutability).

**Comment by notgull** [comment]
1.5.2 has been released
