### ISSUE TITLE
Can you give me an example on how to spawn tasks in a loop but limit total number of tasks?

### ISSUE THREAD

**Issue by halvors** [smol-rs/async-executor#58]
Can you give me an example on how to spawn tasks in a loop but limit total number of tasks?

I want to spawn async tasks from a loop iterating over a huge amount of data, in order to utilize all my CPU cores and execute the tasks in parallell.
How can i make sure i don't spawn more than x amount of tasks?
If to many tasks are spawned they are rejected, i assume there is a max amount of async tasks that can exist at once?

Is there a way to limit this by making the iteration wait for more "spots" to be available in the async tasks list?

**Comment by notgull** [comment]
There is no limit to the number of tasks that can be spawned on an `async` executor. I've opened #59 to explain how `async-executor` can limit its task count.
