### ISSUE TITLE
BorrowError on a server with a huge amount of tasks

### ISSUE THREAD

**Issue by nullchinchilla** [smol-rs/async-executor#60]
I am seeing my server crash very occasionally like this:

```
Oct 15 17:21:49 sd-177498 geph4-exit-start[26711]: thread 'sscale-wkr-c' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.4/src/lib.rs:950:49:
Oct 15 17:21:49 sd-177498 geph4-exit-start[26711]: already mutably borrowed: BorrowError
Oct 15 17:21:49 sd-177498 geph4-exit-start[26711]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by notgull** [comment]
I'm starting to think that the new thread local code isn't worth the trouble, as it's added a new layer of complexity to the executor.

**Comment by nullchinchilla** [comment]
Yeah, I think keeping `async-executor` simple is the right solution, especially because more complex executors with any sort of "thread-local" logic are *extremely* hard to make compatible with nested executors. Typically I just use `smolscale` as my global executor but `smol::Executor` for local executors
